### PR TITLE
Add a storybook example for Window with close.

### PR DESCRIPTION
**Pull request by christoshrousis**
Not sure if appropriate, but will a button in a header work to address issue #15 

I don't really think it needs some special prop. You can attach actions to it like a standard button.

### CODE REVIEW

**Comment by arturbien** [comment]
@christoshrousis thanks man, that's actually a good idea! 🚀 I have some suggestions tho:
* Can you just add the close button to the existing 'default' story? I think it's better to show it in the default one instead of creating another story.
* also, please add these styles to the button itself:  `marginRight: -6px  marginTop: 1px`  (it looks way better this way).

**Comment by christoshrousis** [comment]
Hey mate, that's been updated.

**Pull request merged**
