### PR TITLE
Implement Tree component

### PR DESCRIPTION
**Pull request by alpavlove**
Resolves https://github.com/arturbien/React95/issues/209 (add Tree component)

### CODE REVIEW

**Comment by arturbien** [comment]
@alpavlove thanks for PR! I will try to review it over the weekend 🚀

**Comment by alpavlove** [comment]
Hi @arturbien. I'm really looking forward to receiving feedback and getting the this merged

**Comment by arturbien** [comment]
@alpavlove really sorry for the delay. been super busy lately. hopefully this weekend I'll find the time to go through. this

**Comment by arturbien** [comment]
@alpavlove first of all - great job 🔥 I've picked up some things that should be changed:

- Folder items are not focused when tabbing throught the tree (In below example `latte` and `espresso` is skipped when tabbing throught the items. Or is it because there's no callback specified for those items?)

https://user-images.githubusercontent.com/28541613/168461291-6a2a63d4-5821-4bae-9b1c-48f3b7b39199.mov


- Make the dotted tree path 2px wide instead of 1px wide (React95 uses a bit wider borders/lines compared to OG win 95)
- Make the expand/collapse icon box to have 2px border width

- A subtree should be expanded right below the icon, not below the 'expand/collapse' icon
- Focus styles should be different. Instead of using 1px dotted border around entire item, use focus styles as shown below (navy background with yellow dotted outline) around item label. You can find the same styles used in `<Select />` component once user selects a new value in the dropdown

Screenshot 2022-05-15 at 09 16 17
Screenshot 2022-05-15 at 09 19 40

For reference you can run this awesome Windows 95 emulator and have the OG Tree for reference there: https://www.pcjs.org/software/pcx86/sys/windows/win95/4.00.950/

**Review by arturbien — CHANGES_REQUESTED** [review]
@alpavlove first of all - great job 🔥 I've picked up some things that should be changed:

- Folder items are not focused when tabbing throught the tree (In below example `latte` and `espresso` is skipped when tabbing throught the items. Or is it because there's no callback specified for those items?)

https://user-images.githubusercontent.com/28541613/168461291-6a2a63d4-5821-4bae-9b1c-48f3b7b39199.mov


- Make the dotted tree path 2px wide instead of 1px wide (React95 uses a bit wider borders/lines compared to OG win 95)
- Make the expand/collapse icon box to have 2px border width

- A subtree should be expanded right below the icon, not below the 'expand/collapse' icon
- Focus styles should be different. Instead of using 1px dotted border around entire item, use focus styles as shown below (navy background with yellow dotted outline) around item label. You can find the same styles used in `<Select />` component once user selects a new value in the dropdown

Screenshot 2022-05-15 at 09 16 17
Screenshot 2022-05-15 at 09 19 40

For reference you can run this awesome Windows 95 emulator and have the OG Tree for reference there: https://www.pcjs.org/software/pcx86/sys/windows/win95/4.00.950/

**Comment by alpavlove** [comment]
@arturbien thanks for the detailed feedback. All comments should be resolved now. The emulator is really awesome :D

**Comment by arturbien** [comment]
@alpavlove sheeesh now it looks way better! 
I'll still bother you some more because I've found couple minor issues. I'll give you an update during the weekend. 🤓

**Comment by alpavlove** [comment]
@arturbien thanks. I'm really looking forward to getting this done

**Comment by alpavlove** [comment]
Hey @arturbien. That's a friendly reminder to give an update 🙂 Thanks in advance

**Comment by arturbien** [comment]
@alpavlove sorry for being so slow with responses. I got deadlines in two projects that I am working on rn 🥵. Will do before the end of the week

**Comment by arturbien** [comment]
@alpavlove 
1. The expand/collapse (+ / -) placement is wrong. It should be placed on the vertical line, not next to it:
Screenshot 2022-05-28 at 14 04 30
2. Navy background stays on the item even when it's not focused (it should be only highlighted when it's in focus)

**Comment by alpavlove** [comment]
Thanks for taking your time @arturbien

> 2. Navy background stays on the item even when it's not focused (it should be only highlighted when it's in focus)

I assume you're talking about the state when an item is selected. So the navy outline indicates that and it doesn't seem I should remove that. Any thoughts?

**Comment by arturbien** [comment]
@alpavlove the background and outline should be visible only when an item is focused. You can use Win 95 I linked you before for reference. If user expands tree item but then clicks a button, or anywhere else on the page for that matter, the navy background+outline should be removed from tree item (since it's no longer in focus)

**Comment by alpavlove** [comment]
@arturbien it didn't dispel my concern regarding the selected state. How do we indicate that?

**Comment by alpavlove** [comment]
@arturbien expand/collapse icon has been relocated and the selected item state has been removed

**Comment by arturbien** [comment]
@alpavlove awesome job. we'll finalize this PR this weekend.

**Review by arturbien — DISMISSED** [review]

**Comment by arturbien** [comment]
@alpavlove PR approved but before we merge please squash all commits into one commit with a message "feat: add Tree component" 🚀

**Comment by alpavlove** [comment]
@arturbien sure thing. It's done. Thanks for your time!

**Review by arturbien — APPROVED** [review]

**Pull request merged**
