### PR TITLE
build: configure rollup-plugin-dts to use special compilerOptions

### PR DESCRIPTION
**Pull request by WesSouza**
An alternative to #329, passing specific TypeScript `compilerOptions` to `rollup-plugin-dts`.

### CODE REVIEW

**Comment by WesSouza** [comment]
@arturbien @luizbaldi although this exported files on the correct locations, it still didn't generate one file per theme as expected.

Any objection to either:
- Export one bundle with all themes in one object
- Export the themes together with `react95` and only have one entry

**Comment by arturbien** [comment]
Ideally we should expose all components and themes in a way that would allow devs to import only the things they need (like MUI does):
```
import Button from '@mui/material/Button';
```

I am worried that if we bundle themes together, we're going to increase the bundle size. Especially if we keep adding more and more themes. I'll try to look into that during the weekend.

@luizbaldi any ideas?

**Comment by WesSouza** [comment]
@arturbien then we need to change rollup for the main entry too, it currently bundles the entire file into one export.

**Comment by WesSouza** [comment]
#329 works nicely now.

**Pull request closed without merging**
