### PR TITLE
Cutout component fixed in the docs

### LINKED ISSUE #192: Cutout component not looking good on the docs
The `Cutout` component is not looking exactly like we want, this is probably related to styling and might be a good opportunity for a first contribution.

Current looking:
Screen Shot 2020-10-06 at 09 53 09

Expected looking (you can check [storybook](https://storybook.react95.io/?path=/story/cutout--default)):
Screen Shot 2020-10-06 at 09 52 45

### How to reproduce:
1. Fork and clone the repo
2. Install the necessary dependêncies using npm (run `npm i` on the root folder) 
3. Start docs locally by running `npm run docs:dev`, this will start a local server running the documentation on `http://localhost:3000/`
4. Navigate to the `Cutout` component through the Menu (Components > Cutout)

### Aditional information
This documentation was written using [Docz](https://www.docz.site) and we structured it following the [colocation](https://kentcdodds.com/blog/colocation) idea, so every component folder has its own documentation file, and everything generally related to the documentation can be found at the `docs/` folder _or_ (this is a known problem) `src/gatsby-theme-docz` that has some Docz only related files used to extend the documentation behavior.

--- 

Before start working on this bug leave a comment here so we can avoid more than one person working on the issue, if you have any doubts feel free to drop a comment here or join us at [Slack](https://join.slack.com/t/react95/shared_invite/enQtOTA1NzEyNjAyNTc4LWYxZjU3NWRiMWJlMGJiMjhkNzE2MDA3ZmZjZDc1YmY0ODdlZjMwZDA1NWJiYWExYmY1NTJmNmE4OWVjNWFhMTE) 🕺

### PR DESCRIPTION
**Pull request by branopuzder**
Fixed imports in Cutout template for docs

Closes #192

### CODE REVIEW

**Comment by arturbien** [comment]
@branopuzder we're using standarized commit messages in order to handle automatic releases and generating changelog. 

We have a command line tool for that. Instead of runnint `git commit` run `git cz` and the tool will walk you through what you have to do. Can you change the commit message?

**Comment by branopuzder** [comment]
@arturbien it should be okay now. Please have a look.

**Comment by arturbien** [comment]
@branopuzder can you make a new pull request with just one commit? I know it's annoying but we need to keep commit history clean 😅

**Comment by branopuzder** [comment]
@arturbien I'll do it

**Pull request closed without merging**
