### PR TITLE
feat(themes): add desktopBackground prop to all themes

### PR DESCRIPTION
**Pull request by tpenguinltg**
This PR partially implements #223. This adds the `desktopBackground` prop to all my themes and also maps `Background` to `desktopBackground` in the Windows theme adapter.

My themes are the low-hanging fruit since the colours are readily available and need little transformation. The themes based on the default Windows themes are next (eventually).

### CODE REVIEW

**Comment by arturbien** [comment]
Thanks for submitting this PR! <3 
I think we should add this `desktopBackground ` prop to every theme in one go. 
I think for now we can just add a teal color (`rgb(84 170 170)`) to every other theme that's not yours. Can you do that in this PR? 🙌

**Comment by tpenguinltg** [comment]
@arturbien Many apologies, I thought I had updated this months ago. I added the proper desktop colours for the stock Windows themes and teal for everything else. I also made components like `Window` use the new theme prop so that it's easy to see the new changes.

**Comment by arturbien** [comment]
@tpenguinltg great job. backgrounds looking great 🤓 merged and deployed!

**Pull request merged**
