### PR TITLE
feat(themes): add more themes by tPenguinLTG

### PR DESCRIPTION
**Pull request by arturbien**
Issue: #213

Themes added: 
aiee
ash
blue
cherry
darkTeal
fxDev
hotChocolate
monochrome
polarized
powerShell
raspberry
redWine
seawater
solarizedDark
solarizedLight
stormClouds
wmii

### CODE REVIEW

**Comment by tpenguinltg** [comment]
Apologies, I had let this slip in my busyness. I will make an effort to PR the unpublished ones soon.

**Comment by arturbien** [comment]
@tpenguinltg no worries! as you can see I opted for first converting the themes using the util you've created, and then just exporting the result as literal object. That's because it makes it easier for me to port the themes to react95-native (I can just copy the files 😅 )

**Comment by tpenguinltg** [comment]
That unfortunately would mean more work for v4, but I guess it's easier than what will have to be done for the other themes since we still have the original values. Would you want me to do the same when I PR the new ones?

**Pull request merged**
